enum ActionTypes {
  APPLY_CARD = 'APPLY_CARD',
  APPLY_CARD_SUCCESS = 'APPLY_CARD_SUCCESS',
  APPLY_CARD_ERROR = 'APPLY_CARD_ERROR',
  APPLY_CARD_NOT_FOUND = 'APPLY_CARD_NOT_FOUND',
}

export default ActionTypes;
